server:
  port: 8080
  servlet:
    encoding: #大模型对话中文乱码处理
      charset: UTF-8
      enabled: true
      force: true
spring:
  application:
    name: springaialibabaquickstart # 微服务名称
  ai:
    dashscope: # 大模型三件套指定
      api-key:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      chat:
        options:
          model: qwen3-max